<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo ToDone</title>
    <link href="./css/style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
    <div class="container">
        <h1>Todo or not todo?</h1>
        <p class="title-p">Add a todo? Or not to add a todo... what... todo..</p>
        <form id="done-event" method="post">
            <input type="text" id="item-input" placeholder="Add a todo...">
            <input class="btn add-item-btn" type="submit" name="done-item" value="Add">
        </form>
        <div class="item-box">
            <p>Take out trash</p>
            <div class="item-border"></div>
            <div class="btns-container">
                <div class="btn-box">
                    <form id="done-event" method="post">
                        <input type="hidden" id="id-from-db" name="id-from-db" value="id-from-db">
                        <input class="btn done-item-btn" type="submit" name="done-item" value="Done">
                    </form>
                </div>
                <div class="btn-box">
                    <form id="edit-event" method="post">
                        <input type="hidden" id="id-from-db" name="id-from-db" value="id-from-db">
                        <input class="btn edit-item-btn" type="submit" name="edit-item" value="Edit">
                    </form>
                </div>
                <div class="btn-box">
                    <form id="delete-event" method="post">
                        <input type="hidden" id="id-from-db" name="id-from-db" value="id-from-db">
                        <input class="btn delete-item-btn" type="submit" name="delete-item" value="Delete">
                    </form>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

<?php

    $result = '';
    $task = 0;

    foreach ($allTodos as $todo) {
        $task ++;
        $result .= 'Todo-' . $task . ': ' . $todo['item'] . '<br>';
    }

    echo $result;