<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo ToDone</title>
    <link href="./css/style.css" type="text/css" rel="stylesheet"/>
    <script defer src="./js/jQuery.js"></script>
    <script defer src="./js/sortableMin.js"></script>
    <script defer src="./js/sortable.js"></script>
    <script defer src="./js/deleteTodo.js"></script>
    <script defer src="./js/completedTodo.js"></script>
    <script defer src="./js/reinstateTodo.js"></script>
    <script defer src="./js/editTodo.js"></script>
</head>
<body>
    <div class="outer-container">
    <div id="todoContainer" class="container list-group">
        <h1 id="todo-header">Todo or not todo?</h1>
        <p class="tip-p">//-- Click and drag todos to rearrange // saves in DB --//</p>
        <p class="title-p">To add a todo or not do a todo?</p>
        <form id="add-event" method="post">
            <input type="text" id="item-input" name="todo" placeholder="Add a todo...">
            <input class="btn add-item-btn main-add-btn" type="submit" name="add-item">
        </form>
        <?php echo displayActiveTodos($allTodos); ?>
    </div>
    <div id="todoneContainer" class="container todone-container list-group">
        <h1 id="todone-header">The todone pile!</h1>
        <p class="tip-p">//-- Click and drag todos to rearrange // does not save --//</p>
        <p class="title-todone-p">A todo not todone?<br> Click 'Reinstate' to tundo todo.</p>
        <?php echo displayCompleteTodos($allTodos); ?>
    </div>
    </div>
</body>
</html>

<?php

/**
 * displays an instance for each active todoItem as long as they are not
 * flagged as deleted or complete
 *
 * @param $todos //takes an array of todos
 * @return string //a html string for each relevant todoItem
 */
function displayActiveTodos($todos) {
    $result = '';
    foreach ($todos as $todo) {

        if($todo['delete'] == 0 && $todo['complete'] == 0) {
            $result .= '<div class="item-box list-group-item" data-position="' . $todo['position'] . '" data-id="' . $todo['id'] . '">';
            $result .=      '<p>' . $todo['item'] . '</p>';
            $result .=      '<div id="item-input-' . $todo['id'] . '" class="item-border">';
            $result .=          '<div class="update-item">';
            $result .=              '<input type="text" class="update-input" id="edit-item-' . $todo['id'] . '" placeholder="' . $todo['item'] . '">';
            $result .=              '<button id="submit-edit-' . $todo['id'] . '" class="btn add-item-btn update-item-btn">Save</button>';
            $result .=              '<button id="cancel-edit-' . $todo['id'] . '" type="button" class="btn add-item-btn cancel-btn">Cancel</button>';
            $result .=          '</div>';
            $result .=      '</div>';
            $result .=      '<div class="btns-container">';
            $result .=          '<div class="btn-box">';
            $result .=              '<button id="done-btn" class="btn done-item-btn" name="done-item" data-id="' . $todo['id'] . '" data-item="' . $todo['item'] . '">Done</button>';
            $result .=          '</div>';
            $result .=          '<div class="btn-box">';
            $result .=              '<button id="edit-btn" class="btn edit-item-btn" name="edit-item" data-id="' . $todo['id'] . '" data-item="' . $todo['item'] . '">Edit</button>';
            $result .=          '</div>';
            $result .=          '<div class="btn-box">';
            $result .=              '<button id="delete-btn" class="btn delete-item-btn" name="delete-item" data-id="' . $todo['id'] . '" data-item="' . $todo['item'] . '">Delete</button>';
            $result .=          '</div>';
            $result .=      '</div>';
            $result .= '</div>';
        }
    }
    return $result;
}

/**
 * displays an instance of each todoItem if flagged as complete
 *
 * @param $todos //takes an array of todos
 * @return string //a html string for each relevant todoItem
 */
function displayCompleteTodos($todos) {
    $result = '';
    foreach ($todos as $todo) {

        if($todo['complete'] == 1) {
            $result .= '<div class="item-box todone-item-box list-group-item">';
            $result .=      '<p class="todone-p">' . $todo['item'] . '</p>';
            $result .=      '<div class="item-border"></div>';
            $result .=      '<div class="btns-container todone-btn">';
            $result .=          '<div class="btn-box-complete">';
            $result .=              '<button id="reinstate-btn" class="btn reinstate-item-btn" name="reinstate-item" data-id="' . $todo['id'] . '" data-item="' . $todo['item'] . '">Reinstate</button>';
            $result .=          '</div>';
            $result .=      '</div>';
            $result .= '</div>';
        }
    }
    return $result;
}
